//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula2405_EF_Modelo_Base.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LojaBDContainer3 : DbContext
    {
        public LojaBDContainer3()
            : base("name=LojaBDContainer3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Categorias> Categorias1 { get; set; }
        public virtual DbSet<Categorias1> Categorias11 { get; set; }
        public virtual DbSet<Categorias11> Categorias111 { get; set; }
        public virtual DbSet<Produtos> Produtos1 { get; set; }
        public virtual DbSet<Produtos1> Produtos11 { get; set; }
        public virtual DbSet<Produtos11> Produtos111 { get; set; }
    }
}
